name: Test GitHub Action

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  workflow_dispatch:  # Allows manual execution

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 22f3001028@ds.study.iitm.ac.in
        run: echo "Hello, world!"
